init
dglazkoff/gophkeeper pull request #1
Opened 2024-12-01 10:12 UTC by dglazkoff

2024-12-03 16:12 UTC, dglazkoff commented
Запустить сервер:
docker-build -t gophkeeper .
docker-compose up

Запустить клиент
go run ./cmd/client

2024-12-03 16:13 UTC, dglazkoff commented
Безопасность передачи данных обеспечена TLS

2024-12-05 22:50 UTC, capsulated requested changes
В принципе, всё классно. Всё стартануло, работает)

Главная проблема: нет тестов и документации. Если не godoc, тогда подробный   `README.md` с хорошим описанием принципа реализации по шифрованию, синхронизации, авторизации и т.п. Оставил также несколько комментов по коду.

Небольшая хотелка: было бы круто, что сразу при старте клиент проверяет и выводит сообщение, доступен ли сервер, а не после того как ввёл логи и пароль)))

Также, после фиксов, записывайся на 1-1, продемонстрируешь, расскажешь и финализируем

2024-12-05 22:50 UTC, capsulated commented on certs/server.crt
Сами серты надо перенести в гитигнор

Хорошо бы, если будут скрипты (bash/make/python) для генерации сертификатов, ключей и прочего при старте. А в идеале, конечно, генерить например в `/tmp` директории операционной системы при старте клиента и проверять при его перезапуске

2024-12-05 22:50 UTC, capsulated commented on cmd/client/main.go
> +type Client struct {
⚠️ Клиент и интерфейс надо обязательно убрать из cmd, перенести в пакет (можно в интернал). В `cmd` 
 должно инициализации и запуска, прослушивания сигналов системы, возможно завершение программы, чтение флагов/конфигурации. А бизнес логика и вся инфраструктура внутри приложения в пакетах: в воркерах и доменах

> Как вариант, можно использовать поведенческий паттерн `Команда (Command)`, по желанию, если есть свободное время

2024-12-05 22:50 UTC, capsulated commented on cmd/client/password.go
> +type PasswordControl struct {
Вот как раз воркер, можно под него пакет авторизации создать и сложить туда все воркеры, связанные с авторизацией

2024-12-05 22:50 UTC, capsulated commented on internal/db/s3.go
> +type s3Storage struct {
Немного смущает, что s3 клиент в одном пакете с postgres клиентом... 🤔

2024-12-14 10:54 UTC, merged